blank_issues_enabled: false
contact_links:
  - name: ðŸ“– Documentation
    url: https://github.com/terraform-r1c-modules/terraform-r1c-cdn-cache#readme
    about: Check the documentation before opening an issue
  - name: ðŸ“š ArvanCloud Documentation
    url: https://docs.arvancloud.ir/en/cdn/caching/
    about: Official ArvanCloud CDN Cache documentation
